export const ROLE_CODES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  TRAINER: "TRAINER",
  MOBILIZER: "MOBILIZER",
  PLACEMENT_OFFICER: "PLACEMENT_OFFICER",
  CLIENT: "CLIENT",
  EXECUTIVE: "EXECUTIVE",
}

export const ENTITY_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  DRAFT: "DRAFT",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  COMPLETED: "COMPLETED",
  ON_HOLD: "ON_HOLD",
}

export const EMPLOYEE_STATUS = {
  ACTIVE: "ACTIVE",
  ON_LEAVE: "ON_LEAVE",
  PROBATION: "PROBATION",
  EXITED: "EXITED",
}

export const PROJECT_STATUS = {
  ACTIVE: "ACTIVE",
  MONITORING: "MONITORING",
  COMPLETED: "COMPLETED",
  SUSPENDED: "SUSPENDED",
}

export const CANDIDATE_STATUS = {
  MOBILIZED: "MOBILIZED",
  ENROLLED: "ENROLLED",
  IN_TRAINING: "IN_TRAINING",
  ASSESSED: "ASSESSED",
  CERTIFIED: "CERTIFIED",
  PLACED: "PLACED",
  DROPPED: "DROPPED",
}

export const ATTENDANCE_STATUS = {
  PRESENT: "PRESENT",
  ABSENT: "ABSENT",
  HALF_DAY: "HALF_DAY",
  LEAVE: "LEAVE",
}

export const REQUEST_STATUS = {
  DRAFT: "DRAFT",
  SUBMITTED: "SUBMITTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  PAID: "PAID",
  CLOSED: "CLOSED",
}

export const GRIEVANCE_STATUS = {
  OPEN: "OPEN",
  IN_REVIEW: "IN_REVIEW",
  RESOLVED: "RESOLVED",
  ESCALATED: "ESCALATED",
}

export const PLACEMENT_STATUS = {
  SCHEDULED: "SCHEDULED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
}

export const REVENUE_TYPE = {
  TRAINING_GRANT: "TRAINING_GRANT",
  PLACEMENT_INCENTIVE: "PLACEMENT_INCENTIVE",
  CSR_TRANCHE: "CSR_TRANCHE",
  REIMBURSEMENT: "REIMBURSEMENT",
}

export const PERMISSION_ACTIONS = ["create", "read", "update", "delete", "approve", "export"]

