export const relationshipMap = {
  users: ["employeeId -> employees.id", "roleIds[] -> roles.id"],
  roles: ["permissionIds[] -> permissions.id"],
  employees: ["roleIds[] -> roles.id", "projectIds[] -> projects.id", "centerIds[] -> centers.id", "assignedBatchIds[] -> batches.id"],
  projects: ["fundingAgencyId -> fundingAgencies.id", "schoolId -> schools.id"],
  centers: ["projectId -> projects.id", "managerEmployeeId -> employees.id"],
  batches: ["projectId -> projects.id", "centerId -> centers.id", "trainerEmployeeId -> employees.id"],
  candidates: ["mobilizerEmployeeId -> employees.id"],
  enrollments: ["candidateId -> candidates.id", "projectId -> projects.id", "centerId -> centers.id", "batchId -> batches.id"],
  trainers: ["employeeId -> employees.id", "batchIds[] -> batches.id"],
  mobilizers: ["employeeId -> employees.id", "centerIds[] -> centers.id"],
  placementOfficers: ["employeeId -> employees.id", "projectIds[] -> projects.id", "centerIds[] -> centers.id"],
  placementDrives: ["companyId -> companies.id", "projectId -> projects.id", "centerId -> centers.id", "placementOfficerEmployeeId -> employees.id", "candidateIds[] -> candidates.id"],
  attendance: ["subjectId -> employees.id | candidates.id", "projectId -> projects.id", "centerId -> centers.id", "batchId -> batches.id", "markedByEmployeeId -> employees.id"],
  leaveRequests: ["employeeId -> employees.id", "approverEmployeeId -> employees.id"],
  salaries: ["employeeId -> employees.id", "projectId -> projects.id"],
  reimbursements: ["employeeId -> employees.id", "projectId -> projects.id"],
  tourRequests: ["employeeId -> employees.id", "projectId -> projects.id", "centerId -> centers.id"],
  grievances: ["raisedById -> employees.id | candidates.id", "projectId -> projects.id", "centerId -> centers.id"],
  invoices: ["projectId -> projects.id", "centerId -> centers.id"],
  procurements: ["projectId -> projects.id", "centerId -> centers.id", "requestedByEmployeeId -> employees.id"],
  exposureVisits: ["projectId -> projects.id", "centerId -> centers.id", "batchId -> batches.id", "companyId -> companies.id"],
  notifications: ["recipientUserId -> users.id"],
  auditLogs: ["actorUserId -> users.id"],
  fileUploads: ["ownerId -> polymorphic owner table"],
  testimonials: ["candidateId -> candidates.id", "projectId -> projects.id", "centerId -> centers.id"],
  insurance: ["candidateId -> candidates.id"],
  assessments: ["candidateId -> candidates.id", "batchId -> batches.id"],
  certifications: ["candidateId -> candidates.id", "assessmentId -> assessments.id"],
  revenue: ["projectId -> projects.id", "centerId -> centers.id"],
  dashboardMetrics: ["scopeId -> projects.id | centers.id | batches.id"],
}

export const entityDependencyGraph = [
  "Permission -> Role -> User",
  "Role -> Employee -> Trainer | Mobilizer | PlacementOfficer",
  "FundingAgency -> Project -> Center -> Batch -> Enrollment -> Candidate",
  "Company -> PlacementDrive -> Candidate",
  "Candidate -> Attendance -> Assessment -> Certification -> PlacementDrive",
  "Project -> Invoice | Procurement | Salary | Revenue | DashboardMetrics",
  "Employee -> LeaveRequest | Reimbursement | TourRequest | Grievance | AuditLog",
]

