import {
  ATTENDANCE_STATUS,
  CANDIDATE_STATUS,
  EMPLOYEE_STATUS,
  ENTITY_STATUS,
  GRIEVANCE_STATUS,
  PLACEMENT_STATUS,
  PROJECT_STATUS,
  REQUEST_STATUS,
  REVENUE_TYPE,
  ROLE_CODES,
} from "./enums.js"

export const schemas = {
  User: {
    id: "USR-0001",
    employeeId: "EMP-0001",
    roleIds: ["ROL-0001"],
    email: "user@pantiss.org",
    passwordHash: "mock-only",
    status: ENTITY_STATUS.ACTIVE,
    lastLoginAt: "2026-05-20T09:30:00+05:30",
  },
  Role: {
    id: "ROL-0001",
    code: ROLE_CODES.ADMIN,
    name: "Admin",
    permissionIds: ["PER-0001"],
    scopeType: "GLOBAL | PROJECT | CENTER | BATCH | CLIENT",
  },
  Permission: {
    id: "PER-0001",
    resource: "employee",
    action: "read",
  },
  Employee: {
    id: "EMP-0001",
    employeeCode: "PNT-EMP-0001",
    firstName: "Aditya",
    lastName: "Sahu",
    email: "aditya.sahu@pantiss.org",
    phone: "+91 98765 43210",
    roleIds: ["ROL-0003"],
    projectIds: ["PRJ-0001"],
    centerIds: ["CTR-0001"],
    assignedBatchIds: ["BTH-0001"],
    designation: "Trainer",
    status: EMPLOYEE_STATUS.ACTIVE,
    joinedOn: "2024-04-01",
  },
  FundingAgency: {
    id: "FAG-0001",
    name: "National Skill Development Corporation",
    shortName: "NSDC",
    type: "GOVERNMENT | CSR | FOUNDATION | CLIENT",
    contactEmail: "partnerships@example.org",
  },
  Project: {
    id: "PRJ-0001",
    code: "PMKVY-4",
    name: "PMKVY 4.0 Odisha Skills",
    fundingAgencyId: "FAG-0001",
    schoolId: "SCH-0001",
    startDate: "2025-04-01",
    endDate: "2026-12-31",
    status: PROJECT_STATUS.ACTIVE,
  },
  School: {
    id: "SCH-0001",
    name: "Pantiss School of Livelihoods",
    vertical: "Skill Development",
  },
  Center: {
    id: "CTR-0001",
    projectId: "PRJ-0001",
    name: "Angul Skill Development Center",
    district: "Angul",
    state: "Odisha",
    managerEmployeeId: "EMP-0007",
    status: ENTITY_STATUS.ACTIVE,
  },
  Batch: {
    id: "BTH-0001",
    projectId: "PRJ-0001",
    centerId: "CTR-0001",
    trainerEmployeeId: "EMP-0001",
    code: "ANG-ELEC-101",
    trade: "Electrical Technician",
    capacity: 40,
    startDate: "2026-01-08",
    endDate: "2026-06-30",
    status: ENTITY_STATUS.ACTIVE,
  },
  Candidate: {
    id: "CND-0001",
    firstName: "Sasmita",
    lastName: "Nayak",
    phone: "+91 90000 00001",
    district: "Angul",
    mobilizerEmployeeId: "EMP-0003",
    status: CANDIDATE_STATUS.IN_TRAINING,
  },
  Enrollment: {
    id: "ENR-0001",
    candidateId: "CND-0001",
    projectId: "PRJ-0001",
    centerId: "CTR-0001",
    batchId: "BTH-0001",
    enrolledOn: "2026-01-10",
    status: CANDIDATE_STATUS.IN_TRAINING,
  },
  Trainer: {
    id: "TRN-0001",
    employeeId: "EMP-0001",
    batchIds: ["BTH-0001"],
    specialization: "Electrical Technician",
  },
  Mobilizer: {
    id: "MOB-0001",
    employeeId: "EMP-0003",
    centerIds: ["CTR-0001"],
    villagesCovered: ["Bantala", "Banarpal"],
  },
  PlacementOfficer: {
    id: "PLO-0001",
    employeeId: "EMP-0002",
    projectIds: ["PRJ-0001"],
    centerIds: ["CTR-0001"],
  },
  Company: {
    id: "CMP-0001",
    name: "Tata Motors",
    sector: "Automotive",
    city: "Bhubaneswar",
    status: ENTITY_STATUS.ACTIVE,
  },
  PlacementDrive: {
    id: "DRV-0001",
    companyId: "CMP-0001",
    projectId: "PRJ-0001",
    centerId: "CTR-0001",
    placementOfficerEmployeeId: "EMP-0002",
    candidateIds: ["CND-0001"],
    scheduledOn: "2026-05-28",
    status: PLACEMENT_STATUS.SCHEDULED,
  },
  Attendance: {
    id: "ATD-0001",
    subjectType: "EMPLOYEE | CANDIDATE",
    subjectId: "CND-0001",
    projectId: "PRJ-0001",
    centerId: "CTR-0001",
    batchId: "BTH-0001",
    date: "2026-05-20",
    status: ATTENDANCE_STATUS.PRESENT,
    markedByEmployeeId: "EMP-0001",
  },
  LeaveRequest: {
    id: "LEV-0001",
    employeeId: "EMP-0001",
    fromDate: "2026-05-24",
    toDate: "2026-05-25",
    reason: "Medical",
    status: REQUEST_STATUS.SUBMITTED,
    approverEmployeeId: "EMP-0007",
  },
  Salary: {
    id: "SAL-0001",
    employeeId: "EMP-0001",
    projectId: "PRJ-0001",
    month: "2026-05",
    grossAmount: 32000,
    attendanceDays: 24,
    status: REQUEST_STATUS.APPROVED,
  },
  Reimbursement: {
    id: "RIM-0001",
    employeeId: "EMP-0003",
    projectId: "PRJ-0001",
    category: "Travel",
    amount: 1850,
    status: REQUEST_STATUS.SUBMITTED,
  },
  TourRequest: {
    id: "TOU-0001",
    employeeId: "EMP-0003",
    projectId: "PRJ-0001",
    centerId: "CTR-0001",
    destination: "Bantala Cluster",
    fromDate: "2026-05-27",
    toDate: "2026-05-28",
    status: REQUEST_STATUS.UNDER_REVIEW,
  },
  Grievance: {
    id: "GRV-0001",
    raisedByType: "EMPLOYEE | CANDIDATE",
    raisedById: "CND-0001",
    projectId: "PRJ-0001",
    centerId: "CTR-0001",
    category: "Training",
    status: GRIEVANCE_STATUS.OPEN,
  },
  Invoice: {
    id: "INV-0001",
    projectId: "PRJ-0001",
    centerId: "CTR-0001",
    vendorName: "Sai Catering Services",
    category: "Food and Boarding",
    amount: 320000,
    status: REQUEST_STATUS.SUBMITTED,
  },
  Procurement: {
    id: "PRC-0001",
    projectId: "PRJ-0001",
    centerId: "CTR-0001",
    requestedByEmployeeId: "EMP-0001",
    itemName: "Electrical toolkits",
    quantity: 40,
    estimatedAmount: 96000,
    status: REQUEST_STATUS.UNDER_REVIEW,
  },
  ExposureVisit: {
    id: "EXV-0001",
    projectId: "PRJ-0001",
    centerId: "CTR-0001",
    batchId: "BTH-0001",
    companyId: "CMP-0001",
    visitDate: "2026-05-30",
    status: REQUEST_STATUS.APPROVED,
  },
  Notification: {
    id: "NOT-0001",
    recipientUserId: "USR-0001",
    title: "Placement drive scheduled",
    entityType: "PlacementDrive",
    entityId: "DRV-0001",
    readAt: null,
  },
  AuditLog: {
    id: "AUD-0001",
    actorUserId: "USR-0001",
    action: "CREATE",
    entityType: "Candidate",
    entityId: "CND-0001",
    createdAt: "2026-05-20T10:00:00+05:30",
  },
  FileUpload: {
    id: "FIL-0001",
    ownerType: "Candidate",
    ownerId: "CND-0001",
    fileName: "aadhaar-card.pdf",
    mimeType: "application/pdf",
    url: "/mock-files/aadhaar-card.pdf",
  },
  Testimonial: {
    id: "TST-0001",
    candidateId: "CND-0001",
    projectId: "PRJ-0001",
    centerId: "CTR-0001",
    quote: "The training helped me secure my first formal job.",
    status: REQUEST_STATUS.APPROVED,
  },
  Insurance: {
    id: "INS-0001",
    candidateId: "CND-0001",
    policyNumber: "POL-OD-0001",
    provider: "New India Assurance",
    validFrom: "2026-01-10",
    validTo: "2027-01-09",
  },
  Assessment: {
    id: "ASM-0001",
    candidateId: "CND-0001",
    batchId: "BTH-0001",
    assessor: "Sector Skill Council",
    score: 82,
    status: REQUEST_STATUS.APPROVED,
  },
  Certification: {
    id: "CRT-0001",
    candidateId: "CND-0001",
    assessmentId: "ASM-0001",
    certificateNumber: "CERT-2026-0001",
    issuedOn: "2026-05-15",
  },
  Revenue: {
    id: "REV-0001",
    projectId: "PRJ-0001",
    centerId: "CTR-0001",
    sourceType: REVENUE_TYPE.TRAINING_GRANT,
    amount: 850000,
    recognizedOn: "2026-05-01",
  },
  DashboardMetrics: {
    id: "MET-0001",
    scopeType: "GLOBAL | PROJECT | CENTER | BATCH",
    scopeId: "PRJ-0001",
    candidateCount: 120,
    placementCount: 46,
    attendanceRate: 92,
    revenueRecognized: 850000,
  },
}
