export const EMPLOYEES = [
  {
    id: 1,
    name: "Aditya Sahu",
    role: "Trainer",
    center: "Angul",
    project: "PMKVY 4.0",
    status: "Active",
    phone: "+91 98765 43210",
    email: "aditya.sahu@pantiss.in",
    performance: 94,
  },
  {
    id: 2,
    name: "Meera Das",
    role: "Placement Officer",
    center: "Angul",
    project: "PMKVY 4.0",
    status: "Active",
    phone: "+91 98765 43211",
    email: "meera.das@pantiss.in",
    performance: 89,
  },
  {
    id: 3,
    name: "Rahul Pradhan",
    role: "Mobilizer",
    center: "Jharsuguda",
    project: "CSR - Tata Steel",
    status: "Active",
    phone: "+91 98765 43212",
    email: "rahul.pradhan@pantiss.in",
    performance: 91,
  },
  {
    id: 4,
    name: "Sneha Mohanty",
    role: "Trainer",
    center: "Jharsuguda",
    project: "CSR - Tata Steel",
    status: "On Leave",
    phone: "+91 98765 43213",
    email: "sneha.mohanty@pantiss.in",
    performance: 78,
  },
  {
    id: 5,
    name: "Bikash Naik",
    role: "Placement Officer",
    center: "Kalahandi",
    project: "DDUGKY",
    status: "Active",
    phone: "+91 98765 43214",
    email: "bikash.naik@pantiss.in",
    performance: 84,
  },
  {
    id: 6,
    name: "Sonal Behera",
    role: "Mobilizer",
    center: "Kalahandi",
    project: "DDUGKY",
    status: "Active",
    phone: "+91 98765 43215",
    email: "sonal.behera@pantiss.in",
    performance: 88,
  },
  {
    id: 7,
    name: "Amit Panda",
    role: "Trainer",
    center: "Keonjhar",
    project: "DMF Keonjhar",
    status: "Active",
    phone: "+91 98765 43216",
    email: "amit.panda@pantiss.in",
    performance: 86,
  },
  {
    id: 8,
    name: "Ritika Sahoo",
    role: "Mobilizer",
    center: "Keonjhar",
    project: "DMF Keonjhar",
    status: "Probation",
    phone: "+91 98765 43217",
    email: "ritika.sahoo@pantiss.in",
    performance: 73,
  },
  {
    id: 9,
    name: "Suresh Naik",
    role: "Trainer",
    center: "Sundargarh",
    project: "Shaksham Sundargarh",
    status: "Active",
    phone: "+91 98765 43218",
    email: "suresh.naik@pantiss.in",
    performance: 92,
  },
  {
    id: 10,
    name: "Pooja Patel",
    role: "Placement Officer",
    center: "Sundargarh",
    project: "Shaksham Sundargarh",
    status: "Active",
    phone: "+91 98765 43219",
    email: "pooja.patel@pantiss.in",
    performance: 90,
  },
];

export const SALARY_APPROVALS = [
  { id: "SAL-001", employee: "Aditya Sahu", role: "Trainer", center: "Angul", month: "March 2026", amount: 28600, attendance: 96, target: 100, achievement: 94, status: "Pending" },
  { id: "SAL-002", employee: "Meera Das", role: "Placement Officer", center: "Angul", month: "March 2026", amount: 32400, attendance: 94, target: 45, achievement: 42, status: "Approved" },
  { id: "SAL-003", employee: "Rahul Pradhan", role: "Mobilizer", center: "Jharsuguda", month: "March 2026", amount: 22100, attendance: 91, target: 120, achievement: 108, status: "Pending" },
  { id: "SAL-004", employee: "Amit Panda", role: "Trainer", center: "Keonjhar", month: "March 2026", amount: 27450, attendance: 88, target: 100, achievement: 81, status: "Pending" },
  { id: "SAL-005", employee: "Pooja Patel", role: "Placement Officer", center: "Sundargarh", month: "March 2026", amount: 31800, attendance: 97, target: 40, achievement: 41, status: "Approved" },
  { id: "SAL-006", employee: "Sneha Mohanty", role: "Trainer", center: "Jharsuguda", month: "February 2026", amount: 24800, attendance: 84, target: 100, achievement: 77, status: "Approved" },
  { id: "SAL-007", employee: "Bikash Naik", role: "Placement Officer", center: "Kalahandi", month: "February 2026", amount: 30100, attendance: 89, target: 36, achievement: 29, status: "Pending" },
  { id: "SAL-008", employee: "Sonal Behera", role: "Mobilizer", center: "Kalahandi", month: "February 2026", amount: 21400, attendance: 92, target: 95, achievement: 87, status: "Approved" },
];

export const INVOICES_RAISED = [
  { id: "INV-101", vendor: "Sai Catering Services", category: "Food & Boarding", center: "Angul", project: "PMKVY 4.0", amount: 320000, raisedOn: "2026-03-28", dueOn: "2026-04-20", status: "Pending" },
  { id: "INV-102", vendor: "Tata Consumables", category: "Procurement", center: "Jharsuguda", project: "CSR - Tata Steel", amount: 148000, raisedOn: "2026-03-25", dueOn: "2026-04-18", status: "Verified" },
  { id: "INV-103", vendor: "Skill Lab Equipments", category: "Lab Assets", center: "Kalahandi", project: "DDUGKY", amount: 210500, raisedOn: "2026-03-22", dueOn: "2026-04-19", status: "Approved" },
  { id: "INV-104", vendor: "Odisha Hostel Supply", category: "Food & Boarding", center: "Keonjhar", project: "DMF Keonjhar", amount: 186000, raisedOn: "2026-03-20", dueOn: "2026-04-17", status: "Pending" },
  { id: "INV-105", vendor: "Eastern Safety Works", category: "Safety Gear", center: "Sundargarh", project: "Shaksham Sundargarh", amount: 96500, raisedOn: "2026-03-18", dueOn: "2026-04-15", status: "Paid" },
];

export const PROCUREMENT_ITEMS = [
  { id: "PR-201", item: "Welding Machines", requestedBy: "Suresh Naik", center: "Sundargarh", quantity: 6, budget: 180000, urgency: "High", status: "Pending Approval" },
  { id: "PR-202", item: "Projectors", requestedBy: "Aditya Sahu", center: "Angul", quantity: 3, budget: 96000, urgency: "Medium", status: "Vendor Review" },
  { id: "PR-203", item: "Safety Helmets", requestedBy: "Amit Panda", center: "Keonjhar", quantity: 80, budget: 52000, urgency: "High", status: "Approved" },
  { id: "PR-204", item: "Desktop Systems", requestedBy: "Meera Das", center: "Jharsuguda", quantity: 10, budget: 365000, urgency: "Low", status: "Pending Approval" },
];

export const LIVE_FEEDS = [
  { id: "LIVE-1", owner: "Aditya Sahu", role: "Trainer", center: "Angul", project: "PMKVY 4.0", stream: "Electrical Batch-101", startedAt: "09:40 AM", status: "Live" },
  { id: "LIVE-2", owner: "Pooja Patel", role: "Placement Officer", center: "Sundargarh", project: "Shaksham Sundargarh", stream: "Employer Interview Panel", startedAt: "10:05 AM", status: "Live" },
  { id: "LIVE-3", owner: "Rahul Pradhan", role: "Mobilizer", center: "Jharsuguda", project: "CSR - Tata Steel", stream: "Village Mobilization Camp", startedAt: "11:10 AM", status: "Live" },
  { id: "LIVE-4", owner: "Admin Desk", role: "Admin", center: "Kalahandi", project: "DDUGKY", stream: "Center Monitoring Walkthrough", startedAt: "12:00 PM", status: "Queued" },
];

export const ATTENDANCE_OVERVIEW = [
  {
    center: "Angul",
    project: "PMKVY 4.0",
    trainers: { present: 7, total: 8, trend: [8, 7, 7, 8, 6, 7, 7] },
    placementOfficers: { present: 2, total: 2, trend: [2, 2, 1, 2, 2, 2, 2] },
    mobilizers: { present: 5, total: 6, trend: [6, 5, 6, 6, 5, 5, 5] },
    candidates: { present: 148, total: 160, trend: [150, 148, 142, 155, 149, 145, 148] },
  },
  {
    center: "Jharsuguda",
    project: "CSR - Tata Steel",
    trainers: { present: 4, total: 5, trend: [5, 4, 4, 5, 5, 4, 4] },
    placementOfficers: { present: 1, total: 1, trend: [1, 1, 1, 1, 0, 1, 1] },
    mobilizers: { present: 4, total: 5, trend: [5, 5, 4, 3, 4, 4, 4] },
    candidates: { present: 112, total: 126, trend: [120, 118, 115, 110, 108, 111, 112] },
  },
  {
    center: "Kalahandi",
    project: "DDUGKY",
    trainers: { present: 8, total: 10, trend: [10, 9, 8, 8, 9, 10, 8] },
    placementOfficers: { present: 2, total: 2, trend: [2, 1, 2, 2, 2, 1, 2] },
    mobilizers: { present: 6, total: 8, trend: [8, 7, 6, 7, 8, 6, 6] },
    candidates: { present: 171, total: 214, trend: [180, 175, 168, 182, 190, 175, 171] },
  },
  {
    center: "Keonjhar",
    project: "DMF Keonjhar",
    trainers: { present: 5, total: 6, trend: [6, 6, 5, 5, 6, 5, 5] },
    placementOfficers: { present: 1, total: 1, trend: [1, 1, 1, 0, 1, 1, 1] },
    mobilizers: { present: 4, total: 5, trend: [5, 4, 4, 4, 5, 4, 4] },
    candidates: { present: 126, total: 141, trend: [135, 130, 125, 128, 133, 129, 126] },
  },
  {
    center: "Sundargarh",
    project: "Shaksham Sundargarh",
    trainers: { present: 6, total: 7, trend: [7, 6, 6, 7, 6, 7, 6] },
    placementOfficers: { present: 2, total: 2, trend: [2, 2, 2, 1, 2, 2, 2] },
    mobilizers: { present: 5, total: 6, trend: [6, 5, 5, 6, 6, 6, 5] },
    candidates: { present: 167, total: 193, trend: [180, 172, 165, 170, 178, 164, 167] },
  },
];

export const PROJECT_REPORTS = [
  {
    id: "P-001",
    name: "PMKVY 4.0",
    fundingAgency: "NSDC",
    status: "Active",
    startDate: "2025-04-01",
    endDate: "2026-12-31",
    centers: [
      {
        id: "C-ANG",
        name: "Pantiss Skill Resort, Angul",
        location: "Angul",
        manager: "Rakesh Swain",
        jobRoles: ["Electrical", "Fitter", "Solar Technician"],
        employees: 16,
        candidates: 160,
        placementRate: 81,
        attendanceRate: 92,
        grievances: 4,
        performanceMetrics: [
          { label: "Enrollment Achievement", value: "93%" },
          { label: "Assessment Pass Rate", value: "88%" },
          { label: "Placement Conversion", value: "81%" },
          { label: "Retention After 90 Days", value: "74%" },
        ],
        employeeList: ["Aditya Sahu", "Meera Das", "Nihar Ranjan", "Pallavi Nayak"],
        candidateList: ["Batch 101 - 42", "Batch 102 - 38", "Batch 103 - 40", "Batch 104 - 40"],
        grievancesList: ["Hostel food quality follow-up", "Transport allowance pending", "One lab system under repair", "Generator servicing overdue"],
      },
      {
        id: "C-BLG",
        name: "Bolangir Satellite Center",
        location: "Bolangir",
        manager: "Sandhya Mishra",
        jobRoles: ["Retail Sales", "Domestic Data Entry"],
        employees: 11,
        candidates: 118,
        placementRate: 76,
        attendanceRate: 89,
        grievances: 2,
        performanceMetrics: [
          { label: "Enrollment Achievement", value: "86%" },
          { label: "Assessment Pass Rate", value: "84%" },
          { label: "Placement Conversion", value: "76%" },
          { label: "Retention After 90 Days", value: "70%" },
        ],
        employeeList: ["Rina Pattnaik", "Sanjay Das", "Lopamudra Deo"],
        candidateList: ["Batch 201 - 34", "Batch 202 - 41", "Batch 203 - 43"],
        grievancesList: ["Pending hostel mattress replacement", "Need two more trainers"],
      },
    ],
  },
  {
    id: "P-002",
    name: "CSR - Tata Steel",
    fundingAgency: "Tata Steel Foundation",
    status: "Active",
    startDate: "2025-06-15",
    endDate: "2026-09-30",
    centers: [
      {
        id: "C-JSG",
        name: "Jharsuguda Training Center",
        location: "Jharsuguda",
        manager: "Pradip Nanda",
        jobRoles: ["Welder", "Safety", "Industrial Electrician"],
        employees: 14,
        candidates: 126,
        placementRate: 79,
        attendanceRate: 90,
        grievances: 3,
        performanceMetrics: [
          { label: "Enrollment Achievement", value: "91%" },
          { label: "Assessment Pass Rate", value: "87%" },
          { label: "Placement Conversion", value: "79%" },
          { label: "Retention After 90 Days", value: "72%" },
        ],
        employeeList: ["Sneha Mohanty", "Rahul Pradhan", "Tapan Rout"],
        candidateList: ["Batch 301 - 39", "Batch 302 - 44", "Batch 303 - 43"],
        grievancesList: ["Workshop exhaust fan replacement", "Pending biometric sync", "Need new welding gloves"],
      },
    ],
  },
  {
    id: "P-003",
    name: "DDUGKY",
    fundingAgency: "MoRD",
    status: "Monitoring",
    startDate: "2025-01-10",
    endDate: "2026-11-20",
    centers: [
      {
        id: "C-KAL",
        name: "Kalahandi Center",
        location: "Kalahandi",
        manager: "Harsha Nayak",
        jobRoles: ["Retail", "Hospitality", "General Duty Assistant"],
        employees: 18,
        candidates: 214,
        placementRate: 73,
        attendanceRate: 84,
        grievances: 6,
        performanceMetrics: [
          { label: "Enrollment Achievement", value: "88%" },
          { label: "Assessment Pass Rate", value: "82%" },
          { label: "Placement Conversion", value: "73%" },
          { label: "Retention After 90 Days", value: "66%" },
        ],
        employeeList: ["Bikash Naik", "Sonal Behera", "Aparna Sethy", "Prakash Majhi"],
        candidateList: ["Batch 401 - 56", "Batch 402 - 53", "Batch 403 - 52", "Batch 404 - 53"],
        grievancesList: ["Hostel water pump issue", "Three stipend cases pending", "Classroom AC not functional", "Two dropout counselling requests", "Mess vendor renewal pending", "CCTV downtime in corridor"],
      },
    ],
  },
];

export const TRAINER_APPROVALS = [
  { id: "TR-APR-01", trainer: "Aditya Sahu", center: "Angul", requestType: "Exposure Visit Approval", submittedOn: "2026-04-10", batch: "Batch-101", status: "Pending", remarks: "Industry partner consent attached." },
  { id: "TR-APR-02", trainer: "Sneha Mohanty", center: "Jharsuguda", requestType: "Assessment Completion", submittedOn: "2026-04-09", batch: "Batch-303", status: "Reviewed", remarks: "Assessor report uploaded." },
  { id: "TR-APR-03", trainer: "Amit Panda", center: "Keonjhar", requestType: "Lab Consumables", submittedOn: "2026-04-08", batch: "Batch-107", status: "Pending", remarks: "Urgent welding rods restock required." },
  { id: "TR-APR-04", trainer: "Suresh Naik", center: "Sundargarh", requestType: "Attendance Regularization", submittedOn: "2026-04-07", batch: "Batch-205", status: "Approved", remarks: "Biometric sync issue verified and closed." },
];

export const MOBILIZER_APPROVALS = [
  { id: "MB-APR-01", mobilizer: "Rahul Pradhan", center: "Jharsuguda", requestType: "Campaign Budget", submittedOn: "2026-04-12", location: "Block B", status: "Pending", remarks: "Requesting ₹5000 for local awareness camp tent and chairs." },
  { id: "MB-APR-02", mobilizer: "Sonal Behera", center: "Kalahandi", requestType: "Candidate Override", submittedOn: "2026-04-11", location: "GP Panchayat", status: "Approved", remarks: "Age waiver requested for two promising candidates." },
  { id: "MB-APR-03", mobilizer: "Ritika Sahoo", center: "Keonjhar", requestType: "Transport Allowance", submittedOn: "2026-04-10", location: "Zone 3", status: "Pending", remarks: "Travel bill to distant villages for mobilisation." },
];

export const PLACEMENT_APPROVALS = [
  { id: "PL-APR-01", officer: "Meera Das", center: "Angul", requestType: "Placement Drive", submittedOn: "2026-04-13", entity: "Tech Mahindra", status: "Pending", remarks: "Initial term sheet for mass hiring drive." },
  { id: "PL-APR-02", officer: "Bikash Naik", center: "Kalahandi", requestType: "Corporate MoU", submittedOn: "2026-04-11", entity: "L&T Construction", status: "Reviewed", remarks: "Apprenticeship agreement pending final signature." },
  { id: "PL-APR-03", officer: "Pooja Patel", center: "Sundargarh", requestType: "Offer Letter Verification", submittedOn: "2026-04-09", entity: "Jindal Steel", status: "Approved", remarks: "Verified 15 offer letters for the Q3 batch." },
];
