/* ═══════════════════════════════════════════════════════════════
   Grievance Mock Data — Shared across Admin & Super Admin portals
   ═══════════════════════════════════════════════════════════════ */

export const EMPLOYEE_GRIEVANCES = [
  {
    id: "GRV-E001",
    raisedBy: "Aditya Sahu",
    role: "Trainer",
    project: "PMKVY 4.0",
    center: "Angul",
    addressedTo: "Admin",
    category: "Payment Issue",
    subject: "March salary credited late by 10 days",
    description: "My March 2026 salary was credited 10 days after the usual pay date. This caused significant financial difficulties. Please ensure timely salary processing going forward.",
    priority: "High",
    status: "Resolved",
    submittedOn: "2026-03-15",
    resolvedOn: "2026-03-22",
    timeline: [
      { date: "2026-03-15", status: "Open", note: "Grievance submitted by Aditya Sahu" },
      { date: "2026-03-17", status: "Under Review", note: "Assigned to HR & Finance team" },
      { date: "2026-03-22", status: "Resolved", note: "Salary delay fixed. Compensation of ₹500 applied." },
    ],
  },
  {
    id: "GRV-E002",
    raisedBy: "Meera Das",
    role: "Placement Officer",
    project: "PMKVY 4.0",
    center: "Angul",
    addressedTo: "Admin",
    category: "Work Environment",
    subject: "Insufficient travel allowance for remote areas",
    description: "The current travel allowance does not adequately cover costs when visiting remote mining colonies for placement drives. Fuel and accommodation costs have increased significantly.",
    priority: "Medium",
    status: "Under Review",
    submittedOn: "2026-04-02",
    resolvedOn: null,
    timeline: [
      { date: "2026-04-02", status: "Open", note: "Grievance submitted by Meera Das" },
      { date: "2026-04-05", status: "Under Review", note: "Operations team reviewing travel policy" },
    ],
  },
  {
    id: "GRV-E003",
    raisedBy: "Sneha Mohanty",
    role: "Trainer",
    project: "CSR - Tata Steel",
    center: "Jharsuguda",
    addressedTo: "Admin",
    category: "Work Environment",
    subject: "Workshop exhaust fans not functional",
    description: "The exhaust fans in the welding workshop have been non-functional for over two weeks. This creates unsafe working conditions due to fumes. Immediate repair is needed.",
    priority: "High",
    status: "Open",
    submittedOn: "2026-04-20",
    resolvedOn: null,
    timeline: [
      { date: "2026-04-20", status: "Open", note: "Grievance submitted by Sneha Mohanty" },
    ],
  },
  {
    id: "GRV-E004",
    raisedBy: "Rahul Pradhan",
    role: "Mobilizer",
    project: "CSR - Tata Steel",
    center: "Jharsuguda",
    addressedTo: "Admin",
    category: "Policy Concern",
    subject: "Unclear leave policy for field mobilizers",
    description: "The current leave policy does not clearly define provisions for field staff who work on weekends during community drives. Need clarification on compensatory offs.",
    priority: "Low",
    status: "Resolved",
    submittedOn: "2026-03-28",
    resolvedOn: "2026-04-08",
    timeline: [
      { date: "2026-03-28", status: "Open", note: "Grievance submitted by Rahul Pradhan" },
      { date: "2026-04-01", status: "Under Review", note: "HR reviewing compensatory leave policy" },
      { date: "2026-04-08", status: "Resolved", note: "New comp-off policy circulated via email." },
    ],
  },
  {
    id: "GRV-E005",
    raisedBy: "Bikash Naik",
    role: "Placement Officer",
    project: "DDUGKY",
    center: "Kalahandi",
    addressedTo: "Admin",
    category: "Management",
    subject: "Three stipend disbursement cases pending since Feb",
    description: "Three candidates in my batch have not received their stipends since February. I have escalated this twice verbally but no action has been taken.",
    priority: "High",
    status: "Escalated",
    submittedOn: "2026-04-10",
    resolvedOn: null,
    timeline: [
      { date: "2026-04-10", status: "Open", note: "Grievance submitted by Bikash Naik" },
      { date: "2026-04-14", status: "Under Review", note: "Finance team checking records" },
      { date: "2026-04-18", status: "Escalated", note: "Escalated to Super Admin due to delayed resolution" },
    ],
  },
  {
    id: "GRV-E006",
    raisedBy: "Sonal Behera",
    role: "Mobilizer",
    project: "DDUGKY",
    center: "Kalahandi",
    addressedTo: "Admin",
    category: "Harassment",
    subject: "Verbal harassment during village mobilization camp",
    description: "During a recent mobilization camp in Ward 7, I faced verbal harassment from a local leader. No security or support was provided by the center management.",
    priority: "High",
    status: "Under Review",
    submittedOn: "2026-04-22",
    resolvedOn: null,
    anonymous: true,
    timeline: [
      { date: "2026-04-22", status: "Open", note: "Grievance submitted anonymously" },
      { date: "2026-04-24", status: "Under Review", note: "Safety & compliance team investigating" },
    ],
  },
  {
    id: "GRV-E007",
    raisedBy: "Amit Panda",
    role: "Trainer",
    project: "DDUGKY",
    center: "Keonjhar",
    addressedTo: "Admin",
    category: "Work Environment",
    subject: "Lab systems outdated and frequently crashing",
    description: "Five out of ten lab systems in Keonjhar crash frequently during practical sessions. Students are unable to complete coursework on time. New systems were requested three months ago.",
    priority: "Medium",
    status: "Open",
    submittedOn: "2026-04-28",
    resolvedOn: null,
    timeline: [
      { date: "2026-04-28", status: "Open", note: "Grievance submitted by Amit Panda" },
    ],
  },
  {
    id: "GRV-E008",
    raisedBy: "Sanjay Das",
    role: "Trainer",
    project: "PMKVY 4.0",
    center: "Bolangir",
    addressedTo: "Admin",
    category: "Payment Issue",
    subject: "Reimbursement for training materials not processed",
    description: "I purchased training materials worth ₹4,200 for Batch-202 in February. The reimbursement claim was submitted on March 5 but has not been processed yet.",
    priority: "Medium",
    status: "Under Review",
    submittedOn: "2026-04-15",
    resolvedOn: null,
    timeline: [
      { date: "2026-04-15", status: "Open", note: "Grievance submitted by Sanjay Das" },
      { date: "2026-04-19", status: "Under Review", note: "Finance checking reimbursement pipeline" },
    ],
  },
];

export const ADMIN_TO_SUPERADMIN_GRIEVANCES = [
  {
    id: "GRV-A001",
    raisedBy: "Admin (PMKVY 4.0)",
    role: "Admin",
    project: "PMKVY 4.0",
    center: "All Centers",
    addressedTo: "Super Admin",
    category: "Management",
    subject: "Budget allocation delay for Q2 operations",
    description: "The Q2 operational budget for PMKVY 4.0 has not been released despite multiple follow-ups. This is affecting procurement, hostel maintenance, and trainer payments across Angul and Bolangir centers.",
    priority: "High",
    status: "Under Review",
    submittedOn: "2026-04-05",
    resolvedOn: null,
    timeline: [
      { date: "2026-04-05", status: "Open", note: "Grievance raised by PMKVY 4.0 Admin" },
      { date: "2026-04-08", status: "Under Review", note: "Finance director reviewing allocation timeline" },
    ],
  },
  {
    id: "GRV-A002",
    raisedBy: "Admin (CSR - Tata Steel)",
    role: "Admin",
    project: "CSR - Tata Steel",
    center: "Jharsuguda",
    addressedTo: "Super Admin",
    category: "Policy Concern",
    subject: "Trainer-to-student ratio exceeding NSDC norms",
    description: "The trainer-to-student ratio in Jharsuguda has exceeded 1:50 for the last two months due to unfilled trainer positions. This violates NSDC guidelines and affects training quality.",
    priority: "High",
    status: "Open",
    submittedOn: "2026-04-18",
    resolvedOn: null,
    timeline: [
      { date: "2026-04-18", status: "Open", note: "Grievance raised by CSR Tata Steel Admin" },
    ],
  },
  {
    id: "GRV-A003",
    raisedBy: "Admin (DDUGKY)",
    role: "Admin",
    project: "DDUGKY",
    center: "Kalahandi",
    addressedTo: "Super Admin",
    category: "Work Environment",
    subject: "Critical infrastructure issues at Kalahandi center",
    description: "Multiple infrastructure problems at Kalahandi center: hostel water pump broken for 3 weeks, classroom AC non-functional, and CCTV in corridor down. Repeated maintenance requests have gone unaddressed.",
    priority: "High",
    status: "Resolved",
    submittedOn: "2026-03-20",
    resolvedOn: "2026-04-02",
    timeline: [
      { date: "2026-03-20", status: "Open", note: "Grievance raised by DDUGKY Admin" },
      { date: "2026-03-25", status: "Under Review", note: "Infrastructure team dispatched for assessment" },
      { date: "2026-04-02", status: "Resolved", note: "All issues fixed. Preventive maintenance schedule created." },
    ],
  },
  {
    id: "GRV-A004",
    raisedBy: "Admin (PMKVY 4.0)",
    role: "Admin",
    project: "PMKVY 4.0",
    center: "Bolangir",
    addressedTo: "Super Admin",
    category: "Management",
    subject: "Need two additional trainers urgently for Bolangir",
    description: "Bolangir Satellite Center is running with only 1 trainer for 2 active batches. We need at least 2 more trainers urgently to maintain quality standards. Recruitment approval has been pending for 6 weeks.",
    priority: "Medium",
    status: "Under Review",
    submittedOn: "2026-04-12",
    resolvedOn: null,
    timeline: [
      { date: "2026-04-12", status: "Open", note: "Grievance raised by PMKVY 4.0 Admin" },
      { date: "2026-04-16", status: "Under Review", note: "HR reviewing staffing pipeline" },
    ],
  },
];

/* ═══════════════════════════════════════════════════════════════
   People Directory — for @mention picker in grievance forms
   ═══════════════════════════════════════════════════════════════ */

export const GRIEVANCE_PEOPLE_DIRECTORY = [
  // Super Admin
  { name: "Super Admin", role: "Super Admin", project: "All Projects", center: "HQ" },
  { name: "Rajiv Sharma", role: "Super Admin", project: "All Projects", center: "HQ" },

  // Admins
  { name: "Admin (PMKVY 4.0)", role: "Admin", project: "PMKVY 4.0", center: "All Centers" },
  { name: "Admin (CSR - Tata Steel)", role: "Admin", project: "CSR - Tata Steel", center: "Jharsuguda" },
  { name: "Admin (DDUGKY)", role: "Admin", project: "DDUGKY", center: "Kalahandi" },

  // Center Managers
  { name: "Rakesh Swain", role: "Center Manager", project: "PMKVY 4.0", center: "Angul" },
  { name: "Sandhya Mishra", role: "Center Manager", project: "PMKVY 4.0", center: "Bolangir" },
  { name: "Pradip Nanda", role: "Center Manager", project: "CSR - Tata Steel", center: "Jharsuguda" },
  { name: "Harsha Nayak", role: "Center Manager", project: "DDUGKY", center: "Kalahandi" },
  { name: "Amit Panda", role: "Center Manager", project: "DDUGKY", center: "Keonjhar" },

  // Trainers
  { name: "Aditya Sahu", role: "Trainer", project: "PMKVY 4.0", center: "Angul" },
  { name: "Sanjay Das", role: "Trainer", project: "PMKVY 4.0", center: "Bolangir" },
  { name: "Sneha Mohanty", role: "Trainer", project: "CSR - Tata Steel", center: "Jharsuguda" },
  { name: "Deepak Das", role: "Trainer", project: "DDUGKY", center: "Kalahandi" },
  { name: "Suresh Naik", role: "Trainer", project: "DDUGKY", center: "Kalahandi" },
  { name: "Rakesh Mohanty", role: "Trainer", project: "DDUGKY", center: "Kalahandi" },
  { name: "Ritu Mohapatra", role: "Trainer", project: "DDUGKY", center: "Keonjhar" },

  // Placement Officers
  { name: "Meera Das", role: "Placement Officer", project: "PMKVY 4.0", center: "Angul" },
  { name: "Bikash Naik", role: "Placement Officer", project: "DDUGKY", center: "Kalahandi" },
  { name: "Pooja Patel", role: "Placement Officer", project: "Shaksham Sundargarh", center: "Sundargarh" },

  // Mobilizers
  { name: "Nihar Ranjan", role: "Mobilizer", project: "PMKVY 4.0", center: "Angul" },
  { name: "Rahul Pradhan", role: "Mobilizer", project: "CSR - Tata Steel", center: "Jharsuguda" },
  { name: "Sonal Behera", role: "Mobilizer", project: "DDUGKY", center: "Kalahandi" },
  { name: "Ritika Sahoo", role: "Mobilizer", project: "DMF Keonjhar", center: "Keonjhar" },

  // HR & Finance
  { name: "HR Department", role: "HR", project: "All Projects", center: "HQ" },
  { name: "Finance Department", role: "Finance", project: "All Projects", center: "HQ" },
];
